"""Structured shot planning — Phase 1 of the Visual Director roadmap.

Two optional per-block fields, generated by growthos-web inside the EXISTING
script-generation call (no new LLM call, no new provider):

- `shotType` : HOW the plan is framed (`ALLOWED_SHOT_TYPES`).
- `visualPurpose` : WHY the plan exists (`ALLOWED_VISUAL_PURPOSES`).

Both are optional everywhere. A script with neither (every script generated
before this phase, or a `motion_graphics` script where framing doesn't apply)
renders and scores EXACTLY as before — see `analyze_shot_diversity`'s
"nothing to analyze" early return.

`analyze_shot_diversity` is the deterministic, non-AI check consumed by
`engine/quality.score_generation` (final gate) — it mirrors, on the Python
side, the same diversity rules growthos-web's `scriptIssues()` already
enforces before accepting a generation (structural validation on both sides
of the boundary, never a reliance on the model simply complying with the
prompt).
"""
from __future__ import annotations

from collections import Counter

ALLOWED_SHOT_TYPES = {"wide", "medium", "close_up", "insert", "pov"}
ALLOWED_VISUAL_PURPOSES = {
    "hook", "establish", "action", "evidence", "reaction", "explain", "reveal", "payoff", "cta",
}

# Above this share of shot-typed blocks on one single shotType, the video
# reads as monotonous framing rather than a directed sequence.
_DOMINANCE_RATIO = 0.6
# POV is meant to be an occasional device, not a default framing.
_POV_RATIO = 0.25
# Below this many shot-typed blocks, ratio-based checks are too noisy to be
# meaningful (a 1/2 split "dominates" at 50% trivially).
_MIN_BLOCKS_FOR_RATIO_CHECKS = 4


def analyze_shot_diversity(blocks: list[dict]) -> dict:
    """Deterministic, non-AI analysis of `shotType` across a script's blocks.

    Returns `{"available": False}` when no block carries a `shotType` at all
    — an old script, or a style (e.g. `motion_graphics`) where camera framing
    doesn't apply — so callers apply zero penalty and surface zero issues,
    matching today's behavior exactly (backward compatibility).

    Otherwise returns `{"available": True, "issues": [...], "counts": {...}}`.
    `issues` are human-readable, actionable strings — same shape as
    `engine/editorial_quality.py`'s `issues` list, consumed the same way by
    `engine/quality.score_generation`.
    """
    typed = [
        (i, str(b.get("shotType")))
        for i, b in enumerate(blocks)
        if isinstance(b, dict) and str(b.get("shotType") or "") in ALLOWED_SHOT_TYPES
    ]
    if not typed:
        return {"available": False, "issues": []}

    issues: list[str] = []

    # Consecutive identical shotType on adjacent blocks that BOTH carry one —
    # a gap (one of the pair missing shotType) breaks adjacency, so it isn't
    # flagged as a repeat. The later block being the CTA is exempt: a CTA can
    # reuse whatever framing fits the closing line best.
    for (prev_index, prev_shot), (cur_index, cur_shot) in zip(typed, typed[1:]):
        if cur_index != prev_index + 1:
            continue
        if blocks[cur_index].get("role") == "cta":
            continue
        if cur_shot == prev_shot:
            issues.append(
                f"blocs {prev_index + 1}/{cur_index + 1} : shotType '{cur_shot}' répété sur deux plans consécutifs"
            )

    counts = Counter(shot for _, shot in typed)
    total = len(typed)
    if total >= _MIN_BLOCKS_FOR_RATIO_CHECKS:
        dominant_type, dominant_count = counts.most_common(1)[0]
        if dominant_count / total > _DOMINANCE_RATIO:
            issues.append(
                f"shotType '{dominant_type}' domine la vidéo ({dominant_count}/{total} plans) : "
                "varie davantage le cadrage"
            )
        pov_count = counts.get("pov", 0)
        if pov_count / total > _POV_RATIO:
            issues.append(f"shotType 'pov' trop fréquent ({pov_count}/{total} plans) : garde-le occasionnel")

    missing = len(blocks) - total
    if missing:
        issues.append(
            f"{missing} bloc(s) sans shotType alors que d'autres en ont — génération partiellement conforme"
        )

    return {"available": True, "issues": issues, "counts": dict(counts)}
