-- A quiz series keeps the choices made in the one-screen setup. The episode
-- generator copies this object into script.quiz and generates fresh questions.
alter table public.series
  add column content_format text not null default 'standard'
    check (content_format in ('standard', 'quiz')),
  add column quiz_config jsonb;

alter table public.series add constraint series_quiz_config_shape check (
  (content_format = 'standard' and quiz_config is null)
  or
  (content_format = 'quiz'
    and jsonb_typeof(quiz_config) = 'object'
    and coalesce(quiz_config->>'topic', '') <> ''
    and quiz_config->>'recipe' in ('quick', 'true_false', 'riddle', 'logo', 'impossible')
    and (quiz_config->>'question_count')::integer between 1 and 7
    and (quiz_config->>'countdown_seconds')::integer between 1 and 10
    and quiz_config->>'difficulty' in ('easy', 'medium', 'hard', 'progressive'))
);

comment on column public.series.content_format is
  'Format generated by the series. Quiz series use quiz_config as their reusable product setup.';
comment on column public.series.quiz_config is
  'Quiz setup: topic, recipe, question_count, countdown_seconds and difficulty.';
